apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "people-product-stg"
  name: "api-boilerplate"
  labels:
    k8s-app: "api-boilerplate" 
spec:
  selector:
    matchLabels:
      k8s-app: "api-boilerplate"
  replicas: 1
  template:
    metadata:
     labels:
      k8s-app: "api-boilerplate"
    spec:
      containers:
        - name: "api-boilerplate"
          image: peopleproductsacr.azurecr.io/api-boilerplate
          ports:
          - containerPort: 80
          env:
            - name: peopleapicosmosurl
              value: people-api-cosmos-url@azurekeyvault
            - name: peopleapidatabasehost
              value: people-api-database-host@azurekeyvault
            - name: peopleplatform-api-cosmos-key
              value: peopleplatform-api-cosmos-key@azurekeyvault
          volumeMounts:
          - name: token
            mountPath: "var/run/secrets/kubernetes.io/serviceaccount/"
            readOnly: true
      imagePullSecrets:
        - name: acr-registry
      serviceAccountName: service-account-people-produts
      volumes:
        - name: token
          secret:
            secretName: service-account-people-produts-token-x4l7l
