apiVersion: v1
kind: Service
metadata:
  name: api-boilerplate
  namespace: people-product-stg
  labels:
    k8s-app: "api-boilerplate"
spec:
  ports:
  - name: api-boilerplate
    port: 80 # Porta que vai ser exposta
    protocol: TCP
    targetPort: 3000 # Porta que roda o container
  selector:
    k8s-app: "api-boilerplate"
  type: ClusterIP  